### ISSUE TITLE
node app does not stop

### ISSUE THREAD

**Issue by Pappmann** [chovy/node-startup#26]
command node-app stop answer that app stops and node-app status also say is stopped

but nodebb is running, is there any way to fix it?

**Comment by dbellavista** [comment]
See #25 , for a quick fix replace line 56 with:

` echo "cd $APP_DIR && (PORT=$PORT NODE_ENV=$NODE_ENV NODE_CONFIG_DIR=$CONFIG_DIR $NODE_EXEC $APP_DIR/$NODE_APP 1>$LOG_FILE 2>&1 & echo \$! > $PID_FILE)" | sudo -i -u $USER
