### ISSUE TITLE
How to execute script without sudo word in script

### ISSUE THREAD

**Issue by eavelardev** [chovy/node-startup#32]
My "distro" linux (yocto project) not have sudo packet, so when run script cause error because in line 57 use sudo.

My question is how to run script without sudo word. I'm root user.

**Comment by chovy** [comment]
You can probably just modify the script directly and remove the `sudo` references

**Comment by eavelardev** [comment]
When I put:
/etc/init.d/node-app start

Output:
Starting Node app ...
/etc/init.d/node-app: line 57: sudo: command not found
cat: can't open '/home/root/app/pid/app.pid': No such file or directory
Node app started with pid 

Output deleted sudo in line 57:
Starting Node app ...
/etc/init.d/node-app: line 57: -i: command not found
cat: can't open '/home/root/app/pid/app.pid': No such file or directory
Node app started with pid 

deleted sudo reference print error: -i: command not found

**Comment by chovy** [comment]
yeah. don't use sudo and also don't use root user home dir.

**Comment by eavelardev** [comment]
Is the same.

Starting Node app ...
/etc/init.d/node-app: line 57: -i: command not found
cat: can't open '/var/app/pid/app.pid': No such file or directory
Node app started with pid 

the problem is because don't use sudo.
 | sudo -i -u $USER
to 
 | -i -u $USER

-i  is interpreted with a command

**Comment by mplscorwin** [comment]
You will want to comment out that whole line.  It's purpose is to se the
current effective userid.  If run as root, this isn't needed.

**Comment by eavelardev** [comment]
I'm resolve replace 
| sudo -i -u $USER
by
| bash
in the end of line 57.

With this modification, the command is executed by bash program instead of sudo.  

thanks for you suggestions
