### ISSUE TITLE
`is_running` detection implementation

### ISSUE THREAD

**Issue by thetrompf** [chovy/node-startup#40]
Wouldn't it better to leverage the `/proc` filesystem to figure out if the process is running instead of "parsing" `ps` output with `awk` and `grep`?

```shell
is_running() {
    [ -d "/proc/$(get_pid)" ] 
}
```

**Comment by chovy** [comment]
Good idea. Can you submit a PR?

**Comment by thetrompf** [comment]
Yes I can, I'll to it tonight
